# platform = multi_platform_all
# complexity = low
# strategy = configure
# disruption = low
# reboot = false

# the shell module is used because those three commands have to be executed in one Ansible task.
# Othervise the SSH server will be stopped and Ansible will be not able to conect again and continue.

-   name: "{{{ rule_title }}} - reinstall the openssh-server package"
    ansible.builtin.shell:
      cmd: dnf -y remove openssh-server; dnf -y install openssh-server; systemctl restart sshd.service
